class  Test{
	public static void main(String[] args) {
		try
		{
			System.out.println(args[0]);
		}
		catch(Exception e)
		{
			System.out.println("오류 발생");
		}
	}
}
